In [9]:
!pip install requests beautifulsoup4
!pip install lxml

Requirement already satisfied: requests in /opt/mamba/lib/python3.10/site-packages (2.31.0)
Requirement already satisfied: beautifulsoup4 in /opt/mamba/lib/python3.10/site-packages (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/mamba/lib/python3.10/site-packages (from requests) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/mamba/lib/python3.10/site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/mamba/lib/python3.10/site-packages (from requests) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /opt/mamba/lib/python3.10/site-packages (from requests) (2023.11.17)
Requirement already satisfied: soupsieve>1.2 in /opt/mamba/lib/python3.10/site-packages (from beautifulsoup4) (2.5)
Collecting lxml
  Downloading lxml-4.9.4-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (3.7 kB)
Downloading lxml-4.9.4-cp310-cp310-manylinux_2_28_x86_64.whl (7.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 17.1 MB/s eta 0:00:0000:0100:01
Installing collected packages: lxml
Successfully installed lxml-4.9.4

In [10]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

Ce NoteBook permet d'obtenir les tableaux d'émissions de particules fines des véhicules en fonction de leur carburant et de leur norme Euro (que l'on peut facilement retrouver via leur date de mise en circulation). Ces tableaux seront utilisés pour la modélisation.

In [21]:
url = "https://fr.wikipedia.org/wiki/Norme_europ%C3%A9enne_d%27%C3%A9missions"

# Envoi de la requête
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

# Recherche du tableau pour "Diesel"
diesel = soup.find("span", {"id": "V.C3.A9hicules_.C3.A0_moteur_Diesel"}).find_next("table")

# Recherche du tableau pour "Essence"
essence = soup.find("span", {"id": "V.C3.A9hicules_.C3.A0_moteur_essence_et_GPL.2FGNL"}).find_next("table")

# Conversion des tableaux en DataFrames
df_diesel = pd.read_html(str(diesel))[0]
df_essence = pd.read_html(str(essence))[0]

/tmp/ipykernel_1981/936699620.py:14: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_diesel = pd.read_html(str(diesel))[0]
/tmp/ipykernel_1981/936699620.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df_essence = pd.read_html(str(essence))[0]

In [22]:
df_diesel = df_diesel.drop([0, 1, 9], axis = 0)
df_diesel = df_diesel.reset_index()
df_diesel = df_diesel.drop(['index'], axis = 1)

df_diesel.head(10)

,Norme,Euro 1,Euro 2,Euro 3,Euro 4,Euro 5a,Euro 5b,Euro 6b,Euro 6c,Euro 6d -TEMP,Euro 6d
0,Oxydes d'azote (NOx),-,-,500,250,180,180,80,80,80,80
1,Monoxyde de carbone (CO),2 720,1 000,640,500,500,500,500,500,500,500
2,Hydrocarbures (THC),-,-,-,-,-,-,-,-,-,-
3,Hydrocarbures non méthaniques (HCNM),-,-,-,-,-,-,-,-,-,-
4,HC + NOX,970,700,560,300,230,230,170,170,170,170
5,Particules (PM),140,80,50,25,5,45,45,45,45,45
6,Particules (PN) (nb/km),-,-,-,-,6 × 1011,6 × 1011,6 × 1011,6 × 1011,6 × 1011,6 × 1011

In [23]:
df_essence = df_essence.drop([7, 8], axis = 0)

df_essence.head(10)

,Norme,Euro 1,Euro 2,Euro 3,Euro 4,Euro 5[25],Euro 6b[26],Euro 6c,Euro 6d -TEMP,Euro 6d
0,Oxydes d'azote (NOx),-,-,150,80,60,60,60,60,60
1,Monoxyde de carbone (CO),2 720,2 200,2 200,1 000,1 000,1 000,1 000,1 000,1 000
2,Hydrocarbures (HC),-,-,200,100,100,100,100,100,100
3,Hydrocarbures non méthaniques (HCNM),-,-,-,-,68,68,68,68,68
4,HC + NOX,970,500,-,-,-,-,-,-,-
5,Particules (PM),-,-,-,-,5[* 1],5[* 1],45,45,45
6,Particules (PN) (nb/km),-,-,-,-,-,6 × 1012[* 2],6 × 1011,6 × 1011,6 × 1011

In [24]:
df_diesel.to_csv('emissions_diesel.csv', index = False)
df_essence.to_csv('emissions_essence.csv', index = False)